// flow-typed signature: a822184f271af23fe0c2ae256f99b5e6
// flow-typed version: <<STUB>>/react-native-safe-area-view_v0.14.3/flow_v0.100.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-safe-area-view'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-safe-area-view' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-safe-area-view/index.web' {
  declare module.exports: any;
}

declare module 'react-native-safe-area-view/withOrientation' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-safe-area-view/index' {
  declare module.exports: $Exports<'react-native-safe-area-view'>;
}
declare module 'react-native-safe-area-view/index.js' {
  declare module.exports: $Exports<'react-native-safe-area-view'>;
}
declare module 'react-native-safe-area-view/index.web.js' {
  declare module.exports: $Exports<'react-native-safe-area-view/index.web'>;
}
declare module 'react-native-safe-area-view/withOrientation.js' {
  declare module.exports: $Exports<'react-native-safe-area-view/withOrientation'>;
}
